### ISSUE TITLE
Commands in Action Bar Aren't Taking Arguments

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#10]
Both the eval and open actions don't take selected text as an argument when executed through the action bar as compared to when they're executed in the main text area.

**Comment by mytchel** [comment]
Not quite true but yes. They can get them by mace.focus.tab.main but that is horrible. Should we make selections per tab rather than per text box?

**Comment by mytchel** [comment]
From lua selections can be gotten for the whole tab https://github.com/DandyHQ/mace/commit/221722928cdd1b4391e33dd7b69a97400166e4cb
