### ISSUE TITLE
Tab List for Pane

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#11]
How do we want to be able to navigate through tabs? Scrolling? A button like with firefox?

Does anybody want to implement it better than I have? The solution I've currently got is a pretty temporary measure.

**Comment by vkitchen** [comment]
Firefox does a good job of this. There is a new tab button, and each tab has a close button. If there are two many tabs an arrow appears so you can click to scroll through them, or use the scroll wheel.

This seems like it would fit well with Mace.

**Comment by mytchel** [comment]
Have at it then.

I recommend you give each tab a cairo surface with it's name rendered on it then you can copy the surfaces when drawing the list. It would also make finding which tab is clicked easier.

**Comment by mytchel** [comment]
No longer relevant.
