### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#13]
http://plan9.bell-labs.com/wiki/plan9/Mouse_vs._Keyboard/index.html

Regardless, arrow keys would be nice. Look in textbox.c under textboxkeypress. You will need to make sure the cursor is set to a Unicode code point boundary otherwise it will not be drawn. For left and right you could call sequenceget for the four previous or subsequent bytes and work it out from there, as utf8 code points are a maximum of four bytes (I think).

**Comment by vkitchen** [comment]
I agree with you here. Though I believe the modern standard keyboard shortcuts for basic tasks should be included, Ctrl-z, Ctrl-Z, Ctrl-x, Ctrl-c, Ctrl-a, Ctrl-t, Ctrl-w.

This way users can get going with Mace, and then adjust to its superior way of doing things.

**Comment by mytchel** [comment]
We have keyboard short cuts. You can use maceaddkeybinding to add new bindings. They bind from a string in the form of "C-A-Return" or "b" to a command. Just need a way to configure them and some more commands.
