### ISSUE TITLE
Use the System Paste Buffer

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#15]
As it stands now Mace uses an internal paste buffer. It would be nice if you could use the system paste buffer to copy text in and out of Mace.

**Comment by mytchel** [comment]
Any progress?

**Comment by vkitchen** [comment]
Not of recent. I'll get started again once I have that scroll prototype finished.

**Comment by mytchel** [comment]
https://en.wikipedia.org/wiki/X_Window_selection#Cut_buffers
Why did cut buffers die?

**Comment by vkitchen** [comment]
I think they were considered too simple and easy to implement. Therefore they had to be deprecated in order to make X what it is today
