### ISSUE TITLE
Make Scrollbar dragable

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#17]
It would be a lot more intuitive.

**Comment by mytchel** [comment]
http://www.call-with-current-continuation.org/articles/keyboard-vs-mice.html

Scrollbars - the standard scrollbar is an epitome of bad user interface
design. Scrolling through large bodies of text is a pain. In acme,
it's the button that decides where to scroll: B1 (left) scrolls up, B3
(right) down, depending on the position where you click - the further up,
the smaller the amount of scrolling, B3 near the bottom of the scrollbar
scrolls a full page. Clicking and holding B2 (middle) in the "thumb"
does what you expect and moves the visible area.

**Comment by vkitchen** [comment]
I very much like the way Acme does it. It turns the scrollbar into something actually useful for navigating around the document.

If we are to reproduce we re-introduce the middle button which is something I wanted to avoid.

I'm wondering if there's some way to merge the two behaviours. Where moving the mouse after clicking on the scrollbar indicates a Mac like scroll. Whereas releasing it or keeping it in the same place indicates Acme like. How difficult would it be to play around with this? If you'd like I can prototype in Javascript

**Comment by mytchel** [comment]
It'd work but I don't know how nicely. I suspect it will be very unintuitive. You'll end up wanting to move then deciding against it and be moved against your will. The problem is there are only so many buttons, and laptop makers seem to keep removing them. Could introduce a modifier-click but I'd rather keyboard and mouse usage separate. 

What about chording? I can't think of any sensible chords. You can't really chord on a track pad anyway.

We could expose both. Have the acme way for desktop users with real mice, then laptop users with stunted input systems can use modifiers on the keyboard seeing as it is right there for them. Only problem then is for Mac users with those stupid desktop track pads.

Give it a go in JavaScript first.
