### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#2]
Decide on a testing framework and write tests for the code that has been written so far.

**Comment by mytchel** [comment]
We are using Unity. I have written tests for utf8.[c|h] and I am going to write tests for sequence.[c|h]. I do not know what else can be tested?

**Comment by vkitchen** [comment]
I'm not sure either. But I can contribute test coverage tools. We can decide on further tests later I guess. Close issue?

**Comment by mytchel** [comment]
Yeah.
