### ISSUE TITLE
Multiple Cursors and Focus

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#22]
Mace needs some way to edit efficiently. Having to repeat actions is frustrating. So I propose that we add multiple cursors.

With this you could place cursors in different spots, say on multiple lines you've indented wrongly, then perform actions on each of these cursors, say deleting or adding tabs to correct your indentation error.

Any advice or criticisms?

**Comment by vkitchen** [comment]
I like the idea of multiple cursors. I imagine it will prove to be useful, examples I can think would be removing/adding file extensions to a file listing (especially useful if we get renaming integrated). It would also be nice if it integrated with find and replace so that a single replace action could replace all occurrences.

Would Ctrl-Left Click be a suitable shortcut for adding a cursor? It could also be used to toggle already added ones on or off

For indenting I think block select tab makes more sense in most cases. And Shift-Tab to deindent. This would only work in the case where the tab button can be configured to support inserting spaces though.

Do you think this is reachable in the Assignment 4 milestone? I'd consider it lower priority than that.

**Comment by mytchel** [comment]
Yeah I was thinking Ctrl-left click for adding and removing. I'm planning on doing the cursors soon, I don't think they'll be too hard. Block intending might be a bit harder. There isn't really any nice way to find lines. I think it's achievable by assignment 4.

**Comment by mytchel** [comment]
Another thing to define, do we want to be able to have cursors in different text box's at the same time? So you can put a cursor in one window and another in another window and typing goes to both.

**Comment by vkitchen** [comment]
Great. Multiple selections will hold off the need for block indent for now.

If both text boxes are visible then I vote for yes. Actually perhaps it should always be yes, as most of the time clicking will clear the multiple selection, making it hard to accidentally select across tabs.

**Comment by mytchel** [comment]
How do multiple selections hold of block indentation?

> If both text boxes are visible then I vote for yes. Actually perhaps it should always be yes, as most of the time clicking will clear the multiple selection, making it hard to accidentally select across tabs.

That was my thought. So if we do it like that then I was thinking rather than each text box have a cursor or cursors, cursors are global. So when you click away you are losing your cursor. Which could get annoying, especially if you're changing between tabs (but how often will you do that once we get panes. It should be easy enough to put a tab in a visible pane so you don't need to swap between them).

If we allow you to have cursors in multiple text box's then I don't think it makes sense to have click to focus then click to place a cursor as we are discussing in https://github.com/DandyHQ/mace/issues/23

We should probably get Ryan and Hannah's thoughts on this.

**Comment by vkitchen** [comment]
As per your original usage example. You can block indent by using multiple cursors. At least more easily than a single one.

I feel like the proper solution is the idea of both global and local cursors. Ctrl-clicking elevates the most recently used cursor to be global. Clicking would drop the last placed cursor in a text box back to being local.

**Comment by mytchel** [comment]
I don't think I understand what you mean. So Ctrl-click starts creating global cursor, with the last one being the initial global, then you ctrl-click to place more? Then when you click all but the last gets removed and the last one (in the text box you clicked in) gets made local? This sounds very stateful and confusing both for programming and for using.

**Comment by mytchel** [comment]
I feel like Acme's way of focusing would eliminate these problems. You put your mouse in the text box you want typing to go to and it goes there. But once you have multiple cursors in different text box's that should all receive input how do you tell which ones are focused? They're all focused, so click to focus doesn't make much sense. What is the difference between a text box with a cursor that is not receiving input and one that is? You could fade it out but I've never found that very nice.

**Comment by vkitchen** [comment]
Yes that's what I mean. Actually with a Ctrl-Click you could just save all current cursors as local. Turn the most recent into the initial global, and from then on Ctrl-Click only places new globals. When you perform a normal click, all globals go, locals are restored and whichever text box was just clicked into gets a new cursor.

But I agree with the programming difficulty.

**Comment by mytchel** [comment]
So how should commands work? Should it go to the tab/text box that is clicked on or to the focused tab/text box? And what about when you have multiple cursors?

**Comment by mytchel** [comment]
Looking at Emacs it moves the panes cursor when you click as well as focusing that pane. You have to use keyboard short cuts if you want to change the focus without moving the cursor. 

Having the cursor separated from focus could be interesting. It would allow you to put them in one text box, change to another tab and read there while typing in the now not visible text box. This could also be very unintuitive. But I think having a predictable: where you click is where the cursor goes is where the text goes is more important. 

I'm arguing this because it seems more predictable and a lot easier to program. Other ways seem more complicated for both the user and programmer.

**Comment by mytchel** [comment]
0a86e30521f27528e9ef01caa7dd7761035ec8c0 implements this but with middle button as we haven't done any keyboard stuff yet.

**Comment by mytchel** [comment]
As of 0a4035bf5af2e2d4dbed1ad488e70adc1fdef61d it is working nicely and only the method of creating new cursors needs to be changed.
