### ISSUE TITLE
Focus

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#23]
Acme focus's on mouse over but currently Mace focuses on button press with the cursor moving as soon as you press. A more modern way would be to have the first button press change focus and the second change the cursor position.

I don't generally like focusing staying with the cursor. I like being able to move the cursor away from text box I am typing in. However I am undecided as to wither I prefer the Mace's current way of doing things or the way most things handle focusing. It is nice to be able to place the cursor then change focus and have the cursor in the same place when you come back. 

I am asking this because I am thinking of changing how cursors are implemented by making them global to make multiple cursors as in https://github.com/DandyHQ/mace/issues/22 easier to implement.

Do we want to stay how it is, change to mouse over, or change to the modern way?

**Comment by vkitchen** [comment]
I'm not sure I understand the question. Both Mace and Acme seem to follow the standard user input modes (at least on Linux). When focused and the mouse moves out they still accept keyboard input. When unfocused and the mouse moves in they accept scroll input. They also do the expected behaviour from clicking which is to move the cursor.

Is the suggestion to not move the cursor when the window is clicked back on to? I'm not sure I've seen any editor behave this way

**Comment by mytchel** [comment]
Acme is defiantly different to Mace here. In Acme the focus follows the mouse, so if you have the mouse on one window and type it goes there, if you move it to another window it goes in that window. You don't need to click.

So click to focus then click to set the cursor. What about with multiple cursors as in https://github.com/DandyHQ/mace/issues/22#issuecomment-312407631?

**Comment by vkitchen** [comment]
In windows inside of Acme! I now understand.

Acme is very different than all other editors in that regard. I vote for keeping with standard. Click replaces a cursor. Hover allows for scroll. If a user clicks the windows/frames/panes tab it will focus it without moving the cursor.

Just one hiccup. Accidentally losing one cursor when you click back is okay. Losing multiple is a nuisance. Perhaps it should require two clicks to reset the cursor in the case that there are multiple in the window/frame/pane.

**Comment by mytchel** [comment]
Two clicks to reset the cursors sounds like a good idea to me. 
What do you mean by focusing without moving the cursor?

Is there a way to merge issues? We have one discussion going with two issues.

**Comment by mytchel** [comment]
Further discussion in https://github.com/DandyHQ/mace/issues/22
