### ISSUE TITLE
New Config File

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#25]
Now that Lua has been removed it would be niced to have it replaced with a new config file in a different format. Preferably something simple e.g. https://github.com/benhoyt/inih

**Comment by mytchel** [comment]
What should the configuration file control?

Font defiantly. Key bindings once we get them? Default action bar contents not that it matters much yet.

**Comment by vkitchen** [comment]
At this stage. Font...
Perhaps this should be a future goal?

**Comment by mytchel** [comment]
Spaces per tab?

Get it working with font then that's probably about it for now. The default font on my system is disgusting. Though you can just change config.h in the build directory...

**Comment by mytchel** [comment]
Creating our own parser could be a good challenge for @rycoll and @hannahcy?

**Comment by mytchel** [comment]
d994c580303a37c86da03c3b19c52a4be91f8c59
