### ISSUE TITLE
Feature List and UI Design

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#3]
Put a feature list in the read me and 'finalise' our UI goals. 
Write out how we expect users to interact with mace and what they
will be able to do.
Figure out what the goal of mace is.

**Comment by rycoll** [comment]
I've added a little list to the readme that I think sums up most of what we've discussed about the UI. Does it look about right, or are there more features/details I should be putting there?

Also I think I accidentally overwrote some changes you made to the readme Mytchel. I'm not sure how to revert a commit, should I just copy and paste from the previous version and re-commit?? (I have my changes saved elsewhere)

**Comment by mytchel** [comment]
No problem. I've moved my stuff into the wiki instead. Might make it a bit more manageable.

**Comment by vkitchen** [comment]
Mace is in such a good condition that it's now clear how it should be used. Remaining UI design is available in the design repository. The ReadMe now contains a feature list and a TODO list. Remaining issues should be addressed in User Documentation.
