### ISSUE TITLE
Command-line Flags

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#37]
It would be nice to have some support for basic command-line flags. The three most important are --help --verbose and --version along with their short forms.

**Comment by mytchel** [comment]
-v is implemented

**Comment by vkitchen** [comment]
This seems like it will be a reasonable argument parser https://github.com/skeeto/optparse

Whilst it's probably not difficult to write our own parser. When various arguments start combining in short and long form it can become annoying and full of pitfalls. I can think of a few programs that change behaviour depending on argument ordering even though the arguments refer to different stages in the program. So I'd suggest try use a library for now.

**Comment by mytchel** [comment]
Do you want to add this then?

**Comment by vkitchen** [comment]
Done
