### ISSUE TITLE
Auto Indent Is Broken

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#39]
Because symbols are word breaks you can start a line with '##' and then next line will have '##' when it should have nothing. iswordbreak needs to be replaced with iswhitespace which needs to either be implemented or taken from the standard c library. For now it is probably a good idea to implement iswhitespace and have it return true for ' ', '\t'. Could then get rid of the check for islinebreak.

**Comment by vkitchen** [comment]
Was fixed by @rycoll in 7c9e71ceb91adcf1906249e1dbb79ff2e493c029
