### ISSUE TITLE
Pane Resizing

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#4]
Implement pane resizing. Currently all panes are half (vertically or horizontally) the size of their parents.

**Comment by mytchel** [comment]
I removed panes a while ago to make building a little easier. It is probably about time to add them back in if anybody is interested.

**Comment by rycoll** [comment]
I could maybe have a look at this, although I doubt I'll be able to get anything substantial / not-buggy done by Monday.
Would the implementation be like it was before? I vaguely remember how it worked - a binary tree of tabs, marked as horizontally/vertically split?

**Comment by mytchel** [comment]
You could do it however you want but that's how I'd do it.

**Comment by mytchel** [comment]
No longer relevant.
