### ISSUE TITLE
Unbound Special Keys Should Not Enter Text

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#45]
You would not believe how many times I hit Shift-Backspace. At the moment it inputs 'Backspace' into the document. At worst it should no nothing. At best it should be bound to perform Backspace. I imagine this problem also occurs with other uncommon key combinations

**Comment by mytchel** [comment]
Add it to the default keys bindings then. Key name will be "S-BackSpace", for back space the command will be "back". Maybe we should add a command that does nothing or in the command function have a check if the string is NULL and do nothing.
