### ISSUE TITLE
Region Indenting

### ISSUE THREAD

**Issue by mytchel** [DandyHQ/mace#51]
As Vaughan said, some way to indent a selection would be nice.

**Comment by rycoll** [comment]
I just added this. It works with a single cursor, but behaves strangely with multiple cursors, in a way I couldn't quite solve. Any ideas? I'll keep trying to figure it out.

**Comment by mytchel** [comment]
From the looks of it you want to use shiftcursels to move any cursels past the current one along by count otherwise they will stay in their current positions which will now be further back from where you expect them to be. Looks pretty good though.

You should implement shift tab to do the opposite while you're at it :)

**Comment by rycoll** [comment]
Oh right! That makes sense.

**Comment by rycoll** [comment]
Uhh, another question: what's the best way to determine if a given character is '\t'?

**Comment by mytchel** [comment]
sequencecodepoint(s, pos, &code), then compare code to '\t'.

You are probably better of not comparing it to '\t' thought. Some strange people prefer to use space's rather than tabs. I'm sure if you went looking you could also find people that used other characters for indenting. Unicode has more than a few options.

**Comment by rycoll** [comment]
Okay, I think I've finally got this working... except I ended up binding it to Control-Tab instead of Shift, because I couldn't get it working. Does anyone have any ideas on how make S-Tab work?

**Comment by mytchel** [comment]
Should work now. Does this work with multiple cursors?

**Comment by rycoll** [comment]
Sweet.
It *should* work with multiple cursors (seems to). Let me know if anyone finds any bugs!
