### ISSUE TITLE
Arrow keys when past viewpoint has some bugs

### ISSUE THREAD

**Issue by vkitchen** [DandyHQ/mace#52]
I've just noticed it primarily on small files. When cursor is on the last line but not at the end, arrow right scrolls. It also scrolls when arrowing down to the last line even if the body of text doesn't fill the window.

What should arrow down on the last line when there's no more lines do? Should it scroll or just stay there. Scroll may be annoying as you have to move to the mouse to correct

**Comment by mytchel** [comment]
Yeah it's pretty buggy. 

I'd say stay there but seeing as we can scroll so the end is at the top of the screen maybe scroll? I definitely shouldn't move and scroll like it does on the second to last line currently.

**Comment by mytchel** [comment]
Removed for now.
